version: '3.8'

services:

  eureka-server:
    image: eureka-server
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservicios
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false

  config-server:
    image: config-server
    build:
      context: ./config-server
    ports:
      - "8888:8888"
    networks:
      - microservicios
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - eureka-server

  usuarios-servicio:
    image: usuarios-servicio
    build:
      context: ./usuarios-servicio
    ports:
      - "8080:8080"
    networks:
      - microservicios
    depends_on:
      - config-server
      - eureka-server

  asignaturas-servicio:
    image: asignaturas-servicio
    build:
      context: ./asignaturas-servicio
    ports:
      - "8082:8082"
    networks:
      - microservicios
    depends_on:
      - config-server
      - usuarios-servicio
      - eureka-server

networks:
  microservicios:

